# Generated by Django 4.2 on 2024-02-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Верификация'),
        ),
        migrations.AddField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='028378', max_length=6, verbose_name='Код верификации'),
        ),
    ]
