# Generated by Django 4.2 on 2024-02-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='922249', max_length=6, verbose_name='Код верификации'),
        ),
    ]
