# Generated by Django 5.0 on 2024-01-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_published',
            field=models.BinaryField(default=True, verbose_name='Опубликовано'),
        ),
    ]
