# Generated by Django 5.0 on 2024-01-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_published',
        ),
    ]
