# Generated by Django 5.0 on 2024-01-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blog_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_activ',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_published',
            field=models.BinaryField(default=True, verbose_name='ошибочка вышла'),
        ),
    ]
