# Generated by Django 4.2 on 2024-02-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
